### ISSUE TITLE
Some questions about using DP3 for real-world experiments

### ISSUE THREAD

**Issue by cuite1999** [YanjieZe/3D-Diffusion-Policy#10]
Really wonderful work!!!!!!!!!!!!!!!!!
Sorry to bother you, I still have the following questions about conducting real-world experiments on franka. 
1. I want to collect demonstration data of a certain task, use DP3 for training, and then deploy the trained policy to a real-world robot for execution. Is the program for collecting data not included in the github repository? Or just refer to your data format.
2. In the process of deploying the trained policy to the real-world franka robot, is your real-time execution code open source? Can you explain in detail how to deploy it to the real-world franka?
3. Your experiment used a flexible multi-finger gripper. If I only use an ordinary two-finger gripper, do I only need to adjust the parameters of the robot arm's posture? (6+16->6+2) Do other places need to be adjusted?

**Comment by YanjieZe** [comment]
Thank you! :)

1. How to collect data depends on your robots, so we do not provide the code for this part. You could follow the data format we provide. In our work, we mainly use the keyboard to control the robots manually for data collection.
2. The deployment code would be very close to the evaluation script, where you load the trained checkpoint first and execute a Markov decision process. The difference for real robot part is that you need to write your own environment wrapper, and then you could follow our code.
3. Yes, no change. DP3 is a general imitation learning algorithm. Actually our real robot experiments also include using a gripper, and it works well.

**Comment by Ju6276** [comment]
> 真是太棒了!!!!!!!!!!!!!!!!! 抱歉打扰您，关于在franka上进行真实世界实验，我还有以下问题。
> 
> 1. 我想收集某个任务的演示数据，用DP3进行训练，然后将训练好的策略部署到真实世界的机器人上执行。github仓库里没有收集数据的程序吗？或者只是参考你的数据格式。
> 2. 在将训练好的策略部署到真实世界的franka机器人上的过程中，你们的实时执行代码开源了吗？能详细讲解一下如何部署到真实世界的franka上吗？
> 3. 你的实验用的是柔性多指夹爪，如果我只用普通的两指夹爪，是不是只需要调整机械臂姿态的参数？（6+16->6+2）其他地方还需要调整吗？



> Really wonderful work!!!!!!!!!!!!!!!!! Sorry to bother you, I still have the following questions about conducting real-world experiments on franka.
> 
> 1. I want to collect demonstration data of a certain task, use DP3 for training, and then deploy the trained policy to a real-world robot for execution. Is the program for collecting data not included in the github repository? Or just refer to your data format.
> 2. In the process of deploying the trained policy to the real-world franka robot, is your real-time execution code open source? Can you explain in detail how to deploy it to the real-world franka?
> 3. Your experiment used a flexible multi-finger gripper. If I only use an ordinary two-finger gripper, do I only need to adjust the parameters of the robot arm's posture? (6+16->6+2) Do other places need to be adjusted?

hi! Have you used the two-finger gripper in real-space deployment? I output the data of realdex_pour.zarr and found that the state is 7 instead of 6+2=8

**Comment by Ju6276** [comment]
> Really wonderful work!!!!!!!!!!!!!!!!! Sorry to bother you, I still have the following questions about conducting real-world experiments on franka.
> 
> 1. I want to collect demonstration data of a certain task, use DP3 for training, and then deploy the trained policy to a real-world robot for execution. Is the program for collecting data not included in the github repository? Or just refer to your data format.
> 2. In the process of deploying the trained policy to the real-world franka robot, is your real-time execution code open source? Can you explain in detail how to deploy it to the real-world franka?
> 3. Your experiment used a flexible multi-finger gripper. If I only use an ordinary two-finger gripper, do I only need to adjust the parameters of the robot arm's posture? (6+16->6+2) Do other places need to be adjusted?

hi! Have you used the two-finger gripper in real-space deployment? I output the data of realdex_pour.zarr and found that the state is 7 instead of 6+2=8
