### ISSUE TITLE
Question about generating data?

### ISSUE THREAD

**Issue by hschu11** [YanjieZe/3D-Diffusion-Policy#103]
Hello, thanks for your excellent work!
For the MetaWorld tasks, according to the expert model you provided, the `push_back` and `handle-press-side` tasks ran for 20 hours without successfully generating any data, while other tasks were able to construct data normally.
![image](https://github.com/user-attachments/assets/23b42e07-6780-49ad-8a9b-a0060423718a)

**Comment by YanjieZe** [comment]
Hi, thank you for your interest.
You can see that the success times are larger than 0, which means it succeeds. You can change the required success times in the code to be a smaller number, so that you can generate data successfully.

**Comment by hschu11** [comment]
> Hi, thank you for your interest. You can see that the success times are larger than 0, which means it succeeds. You can change the required success times in the code to be a smaller number, so that you can generate data successfully.

Thank you for your reply. By modifying the `success_time`, the `handle-press-side` data can be generated, but the `push-back` task still cannot be generated because its `success_time` is always 0.
![image](https://github.com/user-attachments/assets/3cae658b-e094-4129-80aa-a908aace23c4)
