### ISSUE TITLE
The onedrive link seems to be broken again

### ISSUE THREAD

**Issue by lyxichigoichie** [YanjieZe/3D-Diffusion-Policy#105]
![2e94c3ccfc1595ce971c2ea5ebd7f29](https://github.com/user-attachments/assets/90314476-8eba-460c-8439-15d5889a4f19)

**Comment by lyxichigoichie** [comment]
Could you upload the Adroit RL experts to GoogleDrive ?

Thanks

**Comment by YanjieZe** [comment]
Hi, I can open the link even in the incognito mode of my browser. Could you check whether this is your network problem?
