### ISSUE TITLE
Meta-World benchmark code

### ISSUE THREAD

**Issue by 1223haohao** [YanjieZe/3D-Diffusion-Policy#11]
Hello，thanks for your excellent work!
I want to ask where is the metaworld benchmark code? When I firstly clone the repo, I got rhe code for metaworld.

**Comment by YanjieZe** [comment]
Hi, thank you!

We made some improvements on the meta world env and would release the new version soon. If you have downloaded the previous code, that is also fine to use:)

**Comment by 1223haohao** [comment]
Thank you! Looking forward to your new codes!
