### ISSUE TITLE
Does data need to be in world frame?

### ISSUE THREAD

**Issue by dennisushi** [YanjieZe/3D-Diffusion-Policy#12]
Following the [Converstion script](https://github.com/YanjieZe/3D-Diffusion-Policy/blob/master/scripts/convert_real_robot_data.py), is it strictly necessary to transform the pointcloud to world frame (i.e. we need to do external eye to hand calibration) or not?

**Comment by YanjieZe** [comment]
Hi,
In our experiments, we do calibration to get the camera extrinsics to transform the point cloud into world frames. I think it is ok if you just use depth + intrinsics and do not calibrate (from our experiments it could work also but maybe some performance drop generally)
