### ISSUE TITLE
Why "downsample points by farthest point sampling" instead of other methods (like voxel filter)?

### ISSUE THREAD

**Issue by silencht** [YanjieZe/3D-Diffusion-Policy#13]
Thanks for your excellent work DP3 !  My quesion may be stupid.

**Comment by YanjieZe** [comment]
Hi, good question!

FPS is a commonly-used technique for downsampling, and is clearly better than random sampling in covering the original distribution.

For the method you mention, `voxel filter`, I think it depends on the voxel size? and thus it might be not be a general parameter-free method to use. But certainly, it could be used to replace FPS if you want :)

**Comment by silencht** [comment]
Thank your quick reply !
