### ISSUE TITLE
Data

### ISSUE THREAD

**Issue by SshiJwu** [YanjieZe/3D-Diffusion-Policy#14]
I'd like to know how many demonstrations is needed to train a DP3? I collect about 25 demos and try to train a DP3.  I found that the loss curve converges in 20 minutes and the loss keep stable in later time. I train about 3000 epochs.

**Comment by YanjieZe** [comment]
Hi, 
I think that will depend on your task difficulty. What task are you trying? 

Generally you could try DP3 with just few demonstrations, such as 10~50

**Comment by SshiJwu** [comment]
I want to execute a grasp task. How many epochs do I need to train for 20 demos?

**Comment by YanjieZe** [comment]
2000 epochs could be enough
