### ISSUE TITLE
Question about the experiment in paper

### ISSUE THREAD

**Issue by 1223haohao** [YanjieZe/3D-Diffusion-Policy#15]
Hi,thank you for the excellent work!
I notice that in your paper, there are 2 ways to conduct the experiment.One is the RL-trained agents,the other one is scripted policies.
I think that RL-trained agents method, is to use the expert which you provided in the install.md to generate the episode.
But I am confused what is scripted policies.If you have provided the code of scripted policies

**Comment by YanjieZe** [comment]
Hi, thank you!
Script policies are provided originally by MetaWorld code. Basically it directly plans a path based on raw states, e.g., object positions, goal positions, etc.

**Comment by 1223haohao** [comment]
Got it! 
Thank you!
