### ISSUE TITLE
实验结果达不到，请教下哪里存在问题

### ISSUE THREAD

**Issue by yanghu819** [YanjieZe/3D-Diffusion-Policy#18]
bash scripts/gen_demonstration_adroit.sh pen
bash scripts/train_policy.sh dp3 adroit_pen 0112 0 0
bash scripts/eval_policy.sh dp3 adroit_pen 0112 0 0

checkpoint是： 3D-Diffusion-Policy/3D-Diffusion-Policy/data/outputs/adroit_pen-dp3-0112_seed0/checkpoints/latest.ckpt   

---------------- Eval Results --------------
mean_n_goal_achieved: 9.0500
mean_success_rates: 0.3500
test_mean_score: 0.3500
SR_test_L3: 0.3500
SR_test_L5: 0.3500
---------------- Eval Results --------------                                                                                                                                           
mean_n_goal_achieved: 4.2500                                                                                                                                                           
mean_success_rates: 0.1500                                                                                                                                                             
test_mean_score: 0.1500                                                                                                                                                                
SR_test_L3: 0.1500                                                                                                                                                                     
SR_test_L5: 0.1500

**Comment by YanjieZe** [comment]
The issue is completed as no reply. If any new question, please open new issue. Thanks.
