### ISSUE TITLE
about experiment

### ISSUE THREAD

**Issue by SshiJwu** [YanjieZe/3D-Diffusion-Policy#19]
I used the trained RL model to collect some robot trajectories in IsaacGym. Then I trained a simple_dp3 model, but the task failed, and I wanted to ask what was going on?

**Comment by SshiJwu** [comment]
I train the simple_dp3 model about 3000 epochs, 50 demonstrations.

**Comment by YanjieZe** [comment]
Hi, could you provide more information for better debugging?
Like what task, what your trajectory and observation look like, and how you customize other things.

**Comment by SshiJwu** [comment]
Thanks. I can send you a detailed email explanation. Please tell me your email address.

**Comment by YanjieZe** [comment]
lastyanjieze@gmail.com

**Comment by SshiJwu** [comment]
I have sent to your email.
