### ISSUE TITLE
Reproduce results

### ISSUE THREAD

**Issue by zhouzheyuan** [YanjieZe/3D-Diffusion-Policy#22]
Hi Yanjie, thanks for your great work! 

Currently, I'm reproducing the results of DexArt and I'm noticing that the results seem to be heavily influenced by the generated demonstration. 
![IMG_0030](https://github.com/YanjieZe/3D-Diffusion-Policy/assets/33288145/0d8375b7-5a10-42d4-817f-ae3d5ad1a110)
Specifically, Exp. 0322 and Exp. 0430 used the same demonstration, where Exp. 0430 was repeated five times using different seeds. Exp. 0501 regenerated the demonstration.

It can be seen that the experimental results for the different demonstrations are varied and both are lower than the results reported in the paper. I wonder if there is a way to stabilized reproduction results.

**Comment by YanjieZe** [comment]
Hi, how many demonstrations do you use? In DexArt we actually use 100 demonstrations (see Table III). 

I think the instability is led by the small number of demonstrations. We would consider releasing a few demos so to help better stabilize results.

**Comment by YanjieZe** [comment]
Hi, thank you for reminding:) I have changed that
