### ISSUE TITLE
Clarification on the meaning of action?

### ISSUE THREAD

**Issue by khiemkhanh98** [YanjieZe/3D-Diffusion-Policy#23]
I saw in your readme that ""action": Array of shape (T, Nd), delta action of the robot agent". Does this mean the generated action is a residual and should be added to the previous agent pos to produce the next agent pos? Or the action here is already the next agent pos without needing to add with the previous pos?

**Comment by YanjieZe** [comment]
Hi, this is a good question. In our real-world experiments, we use relative position control, which is what you call "residual action". 

I think the relative position control and the absolute position control are both common practise, and you could try both and select the one that has better performance.
