### ISSUE TITLE
Calibration and normalization

### ISSUE THREAD

**Issue by rakhimovv** [YanjieZe/3D-Diffusion-Policy#24]
Hi, thank you for your work!

Should the camera be calibrated to the robot's base frame to ensure consistency between observation and action? I suppose this is not necessary for joint angles, but what about the position and action of the robot arm (both absolute and relative)?

Also, how does normalization affect this? I assume the normalization must be consistent across the point cloud, agent position, and action. However, it seems like the normalization is handled independently for these fields.

Furthermore, the normalized fields for the datasets Adroit and RealDex are action, agent_pos, and point_cloud. However, for DexArt, the point cloud and Imagin robot are not normalized. Is this to maintain consistency in the concatenated point cloud?

**Comment by YanjieZe** [comment]
Hi, good question. there is no need to calibrate the camera to the robot. You can just put your camera on where you want, and calibrate the camera to get the camera extrinsics and intrinsics. No need to align the camera to the robot.

For the normalization: in our experiments, we find that both with and without the normalization work well. It is suggested to try both to see which is better for your experiments and tasks.

**Comment by YanjieZe** [comment]
Yes, exactly! just make sure your point coulds are aligned between the data collection and the task execution, since you know the cameras always change their position in the lab.

**Comment by rakhimovv** [comment]
Great, thank you!
