### ISSUE TITLE
Why we must to use MultiStepWrapper?

### ISSUE THREAD

**Issue by CAI23sbP** [YanjieZe/3D-Diffusion-Policy#29]
How are you @YanjieZe ?
I read your paper and code.
But i didn't understand about MultiStepWrapper.
It only worked in Evaluation stage, Could you explain why?

**Comment by YanjieZe** [comment]
Hi, this is not our design, but from original Diffusion Policy. Please check their paper for more details: [link](https://diffusion-policy.cs.columbia.edu/). Thanks!

**Comment by CAI23sbP** [comment]
@YanjieZe  thank you for your reply :>
