### ISSUE TITLE
Training on real data?

### ISSUE THREAD

**Issue by dennisushi** [YanjieZe/3D-Diffusion-Policy#3]
Hi, how can I train on the provided real data, e.g. `pour_40demo_1024.zarr`?

**Comment by YanjieZe** [comment]
Hi,

It is almost the same script as training in simulation.

We would provide a tutorial on deploying on the real robot and also the full training script sooner. But basically, the codes are the same.

Best,
Yanjie

**Comment by YanjieZe** [comment]
Hi, we have provided some guidance for training on real robots. Hope that helps :)

**Comment by kingchou007** [comment]
Hi, 

could you please provide a tutorial on deploying on the real robot?
