### ISSUE TITLE
It shows much worse performance than DAPG.

### ISSUE THREAD

**Issue by liops-seungyeob** [YanjieZe/3D-Diffusion-Policy#31]
https://github.com/aravindr93/hand_dapg

Unlike DAPG, after performing the hammer-v01 task, the robot arm loses the hammer.

**Comment by YanjieZe** [comment]
Hi, in our exp, hammer task could be easily finished with 10 demos, and without need of training in environments, unlike DAPG. 
I would possibly suggest double-checking the generated demonstrations and the results you get.
Thank you!
