### ISSUE TITLE
Results on multi-task robot manipulation benckmarks

### ISSUE THREAD

**Issue by hnuzhy** [YanjieZe/3D-Diffusion-Policy#37]
Hi, thanks a lot for releasing your awesome work. Recently, I'm doing experiments to tackle the multi-task robot manipulation problem. Two widely used benckmarks are `RLBench` and `CALVIN`. I'm wondering that if the proposed `DP3` algorithm can be used for tackling this kind of problem or not? Or maybe it can be integrated with some high-level agent planner (e.g., `PerAct`) for decomposing long-horizon instructions to form a possible solver? Looking forward to your reply!

**Comment by YanjieZe** [comment]
Hi, thank you for your interest.
It is surely possible to use DP3 in multi-task benchmarks. In our work, we do not put our focus on this, but it is definitely worth doing. Looking forward your results on this.
