### ISSUE TITLE
Question about the observation key 'imagin_robot'

### ISSUE THREAD

**Issue by yl-wang996** [YanjieZe/3D-Diffusion-Policy#38]
This is a really comprehensive work, and I am trying to do something based on it.

As in the title, I just want to ask, in class [DP3Encoder](https://github.com/YanjieZe/3D-Diffusion-Policy/blob/5fe72ce3d8b4cf6824f43aa5502e6f1e82557c5b/3D-Diffusion-Policy/diffusion_policy_3d/model/vision/pointnet_extractor.py#L204),  there is an attribute `self.imagination_key = 'imagin_robot'`.

What does it mean? and what is used for?

**Comment by YanjieZe** [comment]
See [this issue](https://github.com/YanjieZe/3D-Diffusion-Policy/issues/9)
