### ISSUE TITLE
Question Regarding Ablation Study of the Encoder

### ISSUE THREAD

**Issue by liops-seungyeob** [YanjieZe/3D-Diffusion-Policy#39]
Since the input size of the Diffusion Policy is fixed, the output of the Point Cloud Encoder must also consistently return a fixed value.

It appears that the DP3 and PointNet encoders use Max Pooling to achieve this.

For other encoders, what methods were used to match the input size of the Diffusion Policy?

**Comment by YanjieZe** [comment]
Hi, thank you for your interest.
For other encoders, they all output a latent vector for downstream tasks, so it is similar.
