### ISSUE TITLE
Question about Ablation Experiments

### ISSUE THREAD

**Issue by zuozuojia** [YanjieZe/3D-Diffusion-Policy#42]
Hi, thank you for your great work! 

I have been exploring the codebase and noticed that the `pointnet_type` parameter can only be set to `pointnet`. When attempting to use other values, the code in `pointnet_extractor.py` raises a `NotImplementedError` with the message `pointnet_type: {pointnet_type}`. I wonder if that indicates only the DP3 encoder for point cloud data is currently supported in this repository.

In your paper, you mention Ablation Experiments with other 3D representations such as depth images, RGB-D images, and voxels, as well as DP3 encoder comparisons with other point cloud encoders like PointNet++, Point Transformer, etc. 
Unfortunately, I couldn't find the corresponding code for these implementations in the repository.

Could you please provide guidance on the following:
1. Where can I find the code for processing other 3D representations (depth, RGB-D, voxel, etc.) and their corresponding DP3 encoders?
2. Where is the implementation for the other point cloud encoders (PointNet++, Point Transformer, etc.) mentioned in your paper?

Thank you very much for your time and support.
Best regards!

**Comment by YanjieZe** [comment]
Hi, thank you for your interest. This code base only provides the implementation of DP3.
For other representations, you could refer to their original code.
For example:
- the voxel encoder is from [visual dexterity](https://github.com/Improbable-AI/dexenv). 
- PointNet++ / PointTransformer/PointNeXt are available in [openpoints](https://github.com/guochengqian/pointnext)
- depth is already included, and is encoded by image encoder from Diffusion Policy.
