### ISSUE TITLE
Questions about shape-meta

### ISSUE THREAD

**Issue by Selen-Suyue** [YanjieZe/3D-Diffusion-Policy#52]
I encountered a problem when browsing Adroit_hammer.yaml. Could you tell me shape_meta: &shape_meta
# acceptable types: rgb, low_dim
obs:
# image:
# shape: *image_shape
# type: rgb
point_cloud:
shape: [512, 3]
type: point_cloud
agent_pos:
shape: [24]
type: low_dim
action:
shape: [26]
Are all actions here axis-angle motions?
And what does agent_pos represent?
Also, are the representations of different tasks the same?

**Comment by YanjieZe** [comment]
Hi, thank you for your interest.

Actions are joint positions for hand and end effector positions for arm.

Agent pos includes the similar information, such as joint positions and end effector positions.

Most tasks are the same. It is recommended to use joint positions and eef positions as actions. Please check Diffusion Policy for more details: https://diffusion-policy.cs.columbia.edu/
