### ISSUE TITLE
Bi-Dexhand

### ISSUE THREAD

**Issue by TengBoYuu** [YanjieZe/3D-Diffusion-Policy#53]
Hi, thanks for your great work☺️
I notice that you mentioned Bi-DexHand in your repo，but how should I use this benchmark?

**Comment by YanjieZe** [comment]
Hi, thank you for your interest.

This codebase currently would not support Bi-DexHand. If you are interested, our implementation of Bi-DexHand is a mix of [Eureka](https://github.com/eureka-research/Eureka) and original [Bi-DexHand](https://github.com/PKU-MARL/DexterousHands). You could check these two codebases for reference. 

The point cloud modality tutorial is provided here also: https://github.com/PKU-MARL/DexterousHands/blob/main/docs/point-cloud.md
