### ISSUE TITLE
About test on  DP

### ISSUE THREAD

**Issue by Selen-Suyue** [YanjieZe/3D-Diffusion-Policy#58]
Could you please release the code about testing DP on the benchmarks mentioned in your paper?

**Comment by YanjieZe** [comment]
Hi, thank you for your interest.

For Diffusion Policy, you could refer to their officially released code: https://diffusion-policy.cs.columbia.edu/

**Comment by tlpss** [comment]
Hi @YanjieZe  I am also interested in  the code to reproduce the diffusion policy results on Metaworld. The original codebase DP paper (and codebase) do not test on MetaWorld and therefore it would be helpful if you could release the code for metaworld as well.
