### ISSUE TITLE
Quetion about acquiring Image

### ISSUE THREAD

**Issue by Selen-Suyue** [YanjieZe/3D-Diffusion-Policy#59]
When I try to get images from your simulation, I run into some problems.  In the file 3D-Diffusion-Policy/diffusion_policy_3d/env/adroit/rrl_local/rrl_multicam.py of DP3，I found a bug you marked that needs to be fixed：  
```
def get_stacked_pixels(self): #TODO fix it  
     assert len(self._frames) == self._num_frames          
     stacked_pixels = np.concatenate(list(self._frames), axis=0)  
     return stacked_pixels
```
When I tried to print out the pixels here, I found that the pixels of each frame have been fixed, which means that each frame outputs exactly the same image.  
Likewise, in another part of this file, when I print the image, it outputs the same pixels that repeat in every frame：
```
        else:
            if not self.test_image:
                for cam in self.cameras : # for each camera, render once
                    img = self._env.env.sim.render(width=self.width, height=self.height, mode='offscreen', camera_name=cam, device_id=0) # TODO device id will think later
                    # img = img[::-1, :, : ] # Image given has to be flipped
                    if self.channels_first :
                        img = img.transpose((2, 0, 1)) # then it's 3 x width x height
                    # we should do channels first... (not sure why by default it's not, maybe they did some transpose when using the encoder?)
                    #img = img.astype(np.uint8)
                    # img = Image.fromarray(img) # TODO is this necessary?
                    imgs.append(img)
```
Can I ask for your solution or reference suggestions for the above problems? Because if the above problems are not solved, every picture shown in the demo is actually duplicate content.  
Looking forward to your reply！

**Comment by YanjieZe** [comment]
Hi, thank you for your interest.

I think we only use one camera, so there is only one image here that is being used.  (I am not sure why you got repeated frames.)
