### ISSUE TITLE
Training dynamics

### ISSUE THREAD

**Issue by a-nooj** [YanjieZe/3D-Diffusion-Policy#60]
Hi, thank you for open-sourcing your code.
I'm working on a similar project, integrating point cloud encoding with diffusion, and I'm curious about what your training curves looked like. Did you notice a steep decline in loss initially, followed by it flattening out?
I'm observing that the gradient means and standard deviations for my PointNet encoder are very small, which makes me suspect it's not having much of a conditioning effect on the diffusion process. Did you notice anything similar?

**Comment by a-nooj** [comment]
This is very helpful, I am currently investigating the loss curves for each diffusion step (instead of the aggregate loss) - will keep you updated with my progress!

Sorry if I missed this in the paper, but how long did it take to train for that last 1%?

**Comment by YanjieZe** [comment]
Hi, I think generally we train 2000~3000 epochs. Observing from the loss, I could tell that in only several epochs (~10), the loss has been very small. but we usually still train for long to make our policy accurate
