### ISSUE TITLE
Some details about dp experiment

### ISSUE THREAD

**Issue by Selen-Suyue** [YanjieZe/3D-Diffusion-Policy#61]
When testing the DP effect, which vision model architecture did you choose, CNN or transformer?

**Comment by YanjieZe** [comment]
Hi, thank you for your interest. We use the original vision arch in Diffusion Policy, which is a CNN,

**Comment by Selen-Suyue** [comment]
Hello, could you please tell me if the CNN you used here is based on the Resnet series architecture or if you defined your own convolution blocks? I noticed in the DP3 experiments that a deeper visual model seems to affect the quality of the diffused actions.
