### ISSUE TITLE
生成dexart示例集obj加载错误

### ISSUE THREAD

**Issue by tobocca** [YanjieZe/3D-Diffusion-Policy#62]
运行 bash scripts/gen_demonstration_dexart.sh laptop 时报错 [SAPIEN] [error] Failed to load visual mesh: xxx/3D-Diffusion-Policy/third_party/dexart-release/assets/sapien/10090/textured_objs/new-1.obj.
![image](https://github.com/user-attachments/assets/453e53ee-698b-49d9-a630-2520f7c91c19)
检查后发现缺少new-1.obj这个文件，能否提供呢？不胜感激！
![image](https://github.com/user-attachments/assets/988e6cbf-b98e-45c4-ba5b-f69ef413294d)

**Comment by YanjieZe** [comment]
Hi, would this error influence the running of your program? If not, it is ok. I also encounter similar errors before.

**Comment by tobocca** [comment]
没什么影响，感谢回复！

**Comment by tobocca** [comment]
没什么影响，感谢回复！
