### ISSUE TITLE
I would like to ask about issues related to observation and actions during the  training process.

### ISSUE THREAD

**Issue by tobottyx** [YanjieZe/3D-Diffusion-Policy#65]
![2024-08-28 19-46-28 的屏幕截图](https://github.com/user-attachments/assets/3b2a576b-7854-47a7-8486-e8f793992d65)

"In the above image, there is an `agent_pos` in the observation, which has the same dimension as in the action. What is the difference between the two, and what are they used for, respectively?"
I sincerely hope to receive your response

**Comment by YanjieZe** [comment]
Agent pos is the status of the robot. The action is to control the robot to the target status
