### ISSUE TITLE
convert demo to .zarr

### ISSUE THREAD

**Issue by kangkang2626** [YanjieZe/3D-Diffusion-Policy#67]
Hi, great work. I want to apply dp3 to my own tasks. So first I need to convert the raw data to ".zarr" format. May I ask what is the exact format of your raw data on the real robot? Thank you!
![image](https://github.com/user-attachments/assets/846eba01-5dbf-4a93-8f49-c3558d2c198c)

**Comment by YanjieZe** [comment]
The action is the target robot joints, the visual observation is the point cloud, and the state observation is the current robot joints. You could also use end-effector poses as action/state. 

You could read how we save data as zarr in our code to better understand it. For example: https://github.com/YanjieZe/3D-Diffusion-Policy/blob/master/third_party/VRL3/src/gen_demonstration_expert.py

**Comment by kangkang2626** [comment]
thank you!
