### ISSUE TITLE
isaacgym example

### ISSUE THREAD

**Issue by hjlllll** [YanjieZe/3D-Diffusion-Policy#7]
hi, thanks for your great work, is there any code example for isaacgym env listed in paper?

**Comment by YanjieZe** [comment]
Hi, thanks!

The env wrapper, the env runner, and the data generation script would be almost the same as what we provided for the Adroit env. 

To render point clouds/images for isaacgym envs, you could refer to this nice codebase [bi-dexhands](https://github.com/PKU-MARL/DexterousHands)

**Comment by hjlllll** [comment]
Thanks very much!
