### ISSUE TITLE
a request for docker

### ISSUE THREAD

**Issue by MaltoseFlower** [YanjieZe/3D-Diffusion-Policy#71]
i cannot install all packages successfully all the time. could u guys provider a docker image to help me ?

**Comment by YanjieZe** [comment]
Hi, thank you for your interest. We currently do not use docker yet. If you get some problems, feel free to open an issue/search in the issue/check error_catch.md.

**Comment by abcdsaltfish** [comment]
see #109 .

I made an image in [AutoDL](https://www.codewithgpu.com/i/YanjieZe/3D-Diffusion-Policy/3dp) too.
