### ISSUE TITLE
merging multi-view point clouds

### ISSUE THREAD

**Issue by jiayueru** [YanjieZe/3D-Diffusion-Policy#74]
Hello! I am still encountering issues with merging multi-view point clouds. I tried the fix you provided, but the merging is still unsuccessful. Would it be convenient for you to discuss this further?
![image](https://github.com/user-attachments/assets/68e487eb-0f8a-47a2-af6b-53f146f974c9)

**Comment by YanjieZe** [comment]
Not sure, i think there still might be issues in camera matrices. Welcome to pull a request if you solve this problem!
