### ISSUE TITLE
Question about pytorch3d.

### ISSUE THREAD

**Issue by Samele1234** [YanjieZe/3D-Diffusion-Policy#77]
Thanks to the author for this work. I'm encountering the following problem:

```
pytorch3d_simplified/pytorch3d/_C.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZNK2at6Tensor7is_cudaEv
```

This is my torch version info:

```
pip show torch
Name: torch
Version: 2.4.1+cu121
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: https://pytorch.org/
Author: PyTorch Team
Author-email: packages@pytorch.org
License: BSD-3
Location: /home/user/anaconda3/envs/dp3/lib/python3.8/site-packages
Requires: filelock, fsspec, jinja2, networkx, nvidia-cublas-cu12, nvidia-cuda-cupti-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-runtime-cu12, nvidia-cudnn-cu12, nvidia-cufft-cu12, nvidia-curand-cu12, nvidia-cusolver-cu12, nvidia-cusparse-cu12, nvidia-nccl-cu12, nvidia-nvtx-cu12, sympy, triton, typing-extensions
Required-by: robohive, torchaudio, torchvision
```

Could someone help me with this issue?

**Comment by Samele1234** [comment]
I have already solved this problem using the official PyTorch3D library. Thank you!

**Comment by YanjieZe** [comment]
Sounds good!

**Comment by gentlebear77** [comment]
> I have already solved this problem using the official PyTorch3D library. Thank you!

May I ask which version do you use, it seems that i encounter the same question. Thanks!

**Comment by Samele1234** [comment]
> > I have already solved this problem using the official PyTorch3D library. Thank you!
> 
> May I ask which version do you use, it seems that i encounter the same question. Thanks!

It's 0.7.8.

Name: pytorch3d
Version: 0.7.8
Summary: PyTorch3D is FAIR's library of reusable components for deep Learning with 3D data.
Home-page: https://github.com/facebookresearch/pytorch3d
Author: FAIR
Author-email: 
License: 
Location: /home/user/anaconda3/envs/dp3/lib/python3.8/site-packages/pytorch3d-0.7.8-py3.8-linux-x86_64.egg
Requires: iopath
Required-by:

**Comment by gentlebear77** [comment]
> > > I have already solved this problem using the official PyTorch3D library. Thank you!
> > 
> > 
> > May I ask which version do you use, it seems that i encounter the same question. Thanks!
> 
> It's 0.7.8.
> 
> Name: pytorch3d Version: 0.7.8 Summary: PyTorch3D is FAIR's library of reusable components for deep Learning with 3D data. Home-page: https://github.com/facebookresearch/pytorch3d Author: FAIR Author-email: License: Location: /home/user/anaconda3/envs/dp3/lib/python3.8/site-packages/pytorch3d-0.7.8-py3.8-linux-x86_64.egg Requires: iopath Required-by:

Thank you very much!

**Comment by zcex12138** [comment]
I encountered the same issue, and the official installation method didn't solve it either. However, I managed to fix it by downloading the released package from https://anaconda.org/pytorch3d/pytorch3d/files and installing it with conda.
