### ISSUE TITLE
Question about `n_obs_steps`, `n_action_steps`, and `horizon`

### ISSUE THREAD

**Issue by hesic73** [YanjieZe/3D-Diffusion-Policy#79]
Hi! I'm confused about the relationship between `n_obs_steps`, `n_action_steps`, and `horizon`.

I assumed they correspond to observation horizon, action execution horizon, and action prediction horizon, as described in [Diffusion Policy](https://diffusion-policy.cs.columbia.edu/). However, when I set `n_obs_steps=2`, `n_action_steps=4`, and `horizon=4`, I noticed:

- The observation horizon passed into `compute_loss` is 4 instead of 2.
- The length of the action returned from `predict_action` is 3 instead of 4.

Could you clarify the exact meaning of these parameters and their relationship? Thanks!

![image](https://github.com/user-attachments/assets/3c39d686-e151-4978-abd6-336f6f70ff1a)

**Comment by YanjieZe** [comment]
Hi, thank you for your interest. Only 2 observations are used; and only 3 actions are executed.
