### ISSUE TITLE
question about action

### ISSUE THREAD

**Issue by kangkang2626** [YanjieZe/3D-Diffusion-Policy#81]
Hi, great work. If I want to train my own data with dp3, is it better for action to use relative position or absolute position. Adroit seems to use absolute position. Is it because the amount of change in relative position is so small that the actions are all close to 0 and thus not good for training? Thank you for your answer.

**Comment by YanjieZe** [comment]
Absolute position would be generally better. Also check the original Diffusion Policy paper, where they report similar things.
