### ISSUE TITLE
Question about extrinsics_matrix in convert_real_robot_data.py

### ISSUE THREAD

**Issue by kaijieshi7** [YanjieZe/3D-Diffusion-Policy#82]
Hello. Thank you for your great work.

I noticed that extrinsics_matrix is used in convert_real_robot_data, is this mandatory? Could you kindly explain about how to get this?

Thank you again.

**Comment by YanjieZe** [comment]
Hi, that can be gained from camera calibration. It is used to transform coord system from camera frame to world frame.
But I think without it is also fine, which you can check out our recent work that is not using camera calibration: https://github.com/YanjieZe/Improved-3D-Diffusion-Policy
