### ISSUE TITLE
关于state和action具体元素的含义

### ISSUE THREAD

**Issue by Pepper-FlavoredChewingGum** [YanjieZe/3D-Diffusion-Policy#83]
您好，我正在执行bash scripts/gen_demonstration_adroit.sh hammer指令来生成专家数据。但是我是初学者，不太了解收集数据中state和action具体代表什么意思。比如这24维的state是机器人哪几个关节的pose？旋转和平移是以四元数还是什么格式来存储的？26维的action代表具体什么含义？是否包含位置和速度约束？
真诚期待您的回复！
img shape: (1000, 84, 84, 3), range: [0, 255]
point_cloud shape: (1000, 512, 6), range: [-0.2482137798412634, 255.0]
depth shape: (1000, 84, 84), range: [0.6981372237205505, 2.1000139713287354]
state shape: (1000, 24), range: [-1.2793629169464111, 1.6018180847167969]
action shape: (1000, 26), range: [-0.9999999403953552, 1.0]

**Comment by YanjieZe** [comment]
Hi, thank you for your interest.
We use position control. States and actions are all end-effector positions&rotations + dex hand joints. 
Rotation can be represented in the format you like, such as Euler angles and quaternion.
