### ISSUE TITLE
Question about "Local Condition" and "Global Condition"

### ISSUE THREAD

**Issue by Pepper-FlavoredChewingGum** [YanjieZe/3D-Diffusion-Policy#84]
Thank you for your great work! 
When I read the code, I found that the ConditionalUnet1D network contains global conditions and local conditions, while DP3 takes visual observation as the global condition and does not use local conditions. I want to know when local conditions should be used and when global conditions should be used. Can you give me an example?

**Comment by YanjieZe** [comment]
Hi, thank you for your interest. Local conditions are not used in this code. I think it is actually the original part of Diffusion Policy.
