### ISSUE TITLE
question about  step setting

### ISSUE THREAD

**Issue by Wangbo-CASIA** [YanjieZe/3D-Diffusion-Policy#85]
您好 请教一个问题  dp3.yaml中设置的
horizon: 4
n_obs_steps: 2
n_action_steps: 4
实际获取的每个样本为连续的四帧；
怎么做到 2步观测+4步推理的  （正常我们不应该取连续的6帧吗）

**Comment by YanjieZe** [comment]
it is like this:
| o | o |
| a | a | a | a |
we actually the last 3 actions.

(let me update the config maybe hhh, it makes people confused)

**Comment by Wangbo-CASIA** [comment]
那为啥网络预测的action 依然是(batch, 4, action_dim) 并且我看loss mask也没有对第一个action进行掩码
![Screenshot from 2024-11-11 12-05-47](https://github.com/user-attachments/assets/128c037f-05d1-43f4-9fe5-82233681d073)
