### ISSUE TITLE
question about experiment. performance getting lower when training

### ISSUE THREAD

**Issue by MaltoseFlower** [YanjieZe/3D-Diffusion-Policy#87]
first, thanks for your excellent work!
when i training dp3 on dexart-bucket, i find although the mse is getting lower, the SR rate is getting lower. is that normal? my experiment is in the right way?
![图片](https://github.com/user-attachments/assets/9798f7de-b9bf-49f2-ac9b-840c9c216312)

the below is the result that i generate the demonstration.
![图片](https://github.com/user-attachments/assets/be67584a-abb0-455c-83d9-39b540027315)
![图片](https://github.com/user-attachments/assets/7e8366b6-93ef-4883-8bff-31eb24692c31)

@YanjieZe

**Comment by YanjieZe** [comment]
Hi, thank you for your interest. I guess this might be led by the distribution of expert demonstrations, but I am also not pretty sure. Maybe try to generate different sets of demonstrations to see.
