### ISSUE TITLE
Misalignment Between Real Robot Data State and Point Cloud

### ISSUE THREAD

**Issue by chenzyn** [YanjieZe/3D-Diffusion-Policy#88]
Hi, thank you for open-sourcing your code.
I encountered some issues while reviewing the dataset you uploaded.
From the image I attached, 
- the red points represent the state data read from `zarr_data['data/state']`.
- while the gray points are the scene point cloud read from `zarr_data['data/point_cloud]`.

It is evident that if the state and the point cloud are expressed in the same frame, the red points should align with the corresponding location (end-effector) in the point cloud. However, in the image I provided, the red points are far from the end-effector's position in the point cloud. The point cloud seems to be expressed in a different frame.

So My question is: during the training of DP3, are the point cloud and state expressed in the same frame? Based on the image I attached, it seems they are not. if this is intentional, could you please clarify the reason behind expressing them in different frames?

![Screenshot from 2024-11-20 12-29-46](https://github.com/user-attachments/assets/c9018574-f1e6-4d6b-bced-60993646bc9b)
---
Thank you in advance for your time and assistance!

**Comment by YanjieZe** [comment]
Hi, thank you for your interest. I think they can be in the same frame or in the different frames. In this experiment, we do not align the state to the point cloud frame and it is ok. But I think you could also try to align them to see whether it is helpful (my guess is it would help somehow)
