### ISSUE TITLE
BUG w/ Solution: ERROR Requested gym==0.21.0 has invalid metadata

### ISSUE THREAD

**Issue by Undefinedefity** [YanjieZe/3D-Diffusion-Policy#92]
```
ERROR: Requested gym==0.21.0 from file:///~/3D-Diffusion-Policy/third_party/gym-0.21.0 has invalid metadata: Expected end or semicolon (after version specifier)
    opencv-python>=3.
                 ~~~^
```

This is because no specific `opencv-python` version, go to `3D-Diffusion-Policy/third_party/gym-0.21.0/setup.py` and line 20, add `0` at the end of `opencv-python>=3.` just like this:
![image](https://github.com/user-attachments/assets/ebb2db60-9b95-47ce-b97e-563621e4c6da)

**Comment by YanjieZe** [comment]
Thank you! I have updated the ERROR_CATCH.md based on this issue.
