### ISSUE TITLE
Question about inference time after training using simple_dp3.yaml

### ISSUE THREAD

**Issue by jinyqjinyq** [YanjieZe/3D-Diffusion-Policy#95]
After I trained with simple_dp3.yaml and deployed it on a gpu3090 machine, the inference fps did not reach 25. Most of the inference time was around 110ms. What could be the possible reasons?

**Comment by YanjieZe** [comment]
Hi, I think it is because of your 3090 GPU. 4090/A100 might be faster. But your speed (around 10 fps) seems to be reasonable (a bit slow though).
