### ISSUE TITLE
"wrappers.pxi", line 1071, in mujoco_py.cymj.PyMjModel.camera_name2id ValueError: No "camera" with name top exists. Available "camera" names = ('fixed', 'vil_camera').

### ISSUE THREAD

**Issue by xzhuzhu** [YanjieZe/3D-Diffusion-Policy#99]
Hi, thanks for your great works.
When I am running the code "bash scripts/gen_demonstration_adroit.sh hammer
", I have encountered the following problem:
File "wrappers.pxi", line 1071, in mujoco_py.cymj.PyMjModel.camera_name2id
ValueError: No "camera" with name top exists. Available "camera" names = ('fixed', 'vil_camera').

How can I solved it? The mujoco_py version I used is mujoco_py-2.1.2.14.

**Comment by YanjieZe** [comment]
Hi, It says no such camera. Are you using the adroit environment we provide? or do you maybe do some modifications on the code?

**Comment by xzhuzhu** [comment]
I created a new environment and followed the instructions outlined in the 'INSTALL.md' file to set it up. I did not make any modifications to the process or the environment itself. However, I encountered the issue during the setup. Could you provide some suggestions on how to resolve this problem?

**Comment by YanjieZe** [comment]
Yes. it shows you do not have such camera, so you just need to change a camera that you are using.
